spring:
  config:
    import: application-secret.properties
  datasource:
    url: jdbc:h2:mem:testdb;MODE=MYSQL
    username: sa
    password:
    driver-class-name: org.h2.Driver
  jpa:
    properties:
      hibernate:
        use_sql_comments: true
  h2:
    console:
      enabled: true
      path: /h2-console
  sql:
    init:
      mode: always

custom:
  file:
    csv:
      region:
        path: /sgg_lat_lon.csv