ALTER TABLE member
    MODIFY COLUMN x DECIMAL(15, 9) NULL;

ALTER TABLE member
    MODIFY COLUMN y DECIMAL(15, 9) NULL;

ALTER TABLE restaurant
    MODIFY COLUMN x DECIMAL(15, 9) NOT NULL;

ALTER TABLE restaurant
    MODIFY COLUMN y DECIMAL(15, 9) NOT NULL;